"""init

Revision ID: 160bf4d6dc8a
Revises: 4aeb394c0c1c
Create Date: 2023-12-01 16:10:38.538035

"""

# revision identifiers, used by Alembic.
revision = '160bf4d6dc8a'
down_revision = '4aeb394c0c1c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
