"""init

Revision ID: 249376e26242
Revises: 8ce473871459
Create Date: 2023-12-03 01:28:13.409451

"""

# revision identifiers, used by Alembic.
revision = '249376e26242'
down_revision = '8ce473871459'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
