"""init

Revision ID: 2aa630ca6c48
Revises: d71b7d6174f0
Create Date: 2023-12-03 01:39:53.948155

"""

# revision identifiers, used by Alembic.
revision = '2aa630ca6c48'
down_revision = 'd71b7d6174f0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
