"""init

Revision ID: 2dbe644ff27f
Revises: 847b1adb50ff
Create Date: 2023-12-03 17:26:59.411329

"""

# revision identifiers, used by Alembic.
revision = '2dbe644ff27f'
down_revision = '847b1adb50ff'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
