"""init

Revision ID: 2f3ff0cf1b1f
Revises: 92f8cee6d6bc
Create Date: 2023-12-03 17:34:09.820368

"""

# revision identifiers, used by Alembic.
revision = '2f3ff0cf1b1f'
down_revision = '92f8cee6d6bc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
