"""init

Revision ID: 4aeb394c0c1c
Revises: 83b438fbd135
Create Date: 2023-12-01 16:02:51.353742

"""

# revision identifiers, used by Alembic.
revision = '4aeb394c0c1c'
down_revision = '83b438fbd135'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
