"""init

Revision ID: 509d768ab6f0
Revises: cef50e81b78d
Create Date: 2023-12-03 15:18:55.698541

"""

# revision identifiers, used by Alembic.
revision = '509d768ab6f0'
down_revision = 'cef50e81b78d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
