"""init

Revision ID: 57fbb1030cce
Revises: 2dbe644ff27f
Create Date: 2023-12-03 17:31:44.328740

"""

# revision identifiers, used by Alembic.
revision = '57fbb1030cce'
down_revision = '2dbe644ff27f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
