"""init

Revision ID: 78e74952014b
Revises: 831701d2daca
Create Date: 2023-12-03 15:10:27.047660

"""

# revision identifiers, used by Alembic.
revision = '78e74952014b'
down_revision = '831701d2daca'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
