"""init

Revision ID: 7f84581cc84e
Revises: b9418c818f6f
Create Date: 2023-12-02 22:29:46.111288

"""

# revision identifiers, used by Alembic.
revision = '7f84581cc84e'
down_revision = 'b9418c818f6f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
