"""init

Revision ID: 831701d2daca
Revises: b0c8f59c0344
Create Date: 2023-12-03 14:04:05.575528

"""

# revision identifiers, used by Alembic.
revision = '831701d2daca'
down_revision = 'b0c8f59c0344'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
