"""init

Revision ID: 83b438fbd135
Revises: dd33cb03d01f
Create Date: 2023-12-01 15:44:14.318088

"""

# revision identifiers, used by Alembic.
revision = '83b438fbd135'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
