"""init

Revision ID: 847b1adb50ff
Revises: a4a83836ec4f
Create Date: 2023-12-03 16:26:57.191149

"""

# revision identifiers, used by Alembic.
revision = '847b1adb50ff'
down_revision = 'a4a83836ec4f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
