"""init

Revision ID: 8ce473871459
Revises: 18415af9a752
Create Date: 2023-12-02 23:58:12.230493

"""

# revision identifiers, used by Alembic.
revision = '8ce473871459'
down_revision = '18415af9a752'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
