"""init

Revision ID: 9239fe88089b
Revises: e711c032d713
Create Date: 2023-12-03 02:02:24.164690

"""

# revision identifiers, used by Alembic.
revision = '9239fe88089b'
down_revision = 'e711c032d713'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
