"""init

Revision ID: 92f8cee6d6bc
Revises: 57fbb1030cce
Create Date: 2023-12-03 17:32:33.520053

"""

# revision identifiers, used by Alembic.
revision = '92f8cee6d6bc'
down_revision = '57fbb1030cce'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
