"""init

Revision ID: 942ca8199c39
Revises: 9239fe88089b
Create Date: 2023-12-03 02:07:03.802807

"""

# revision identifiers, used by Alembic.
revision = '942ca8199c39'
down_revision = '9239fe88089b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
