"""init

Revision ID: a4a83836ec4f
Revises: e2e46b3bcdaf
Create Date: 2023-12-03 16:12:23.068931

"""

# revision identifiers, used by Alembic.
revision = 'a4a83836ec4f'
down_revision = 'e2e46b3bcdaf'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
