"""init

Revision ID: b0c8f59c0344
Revises: 942ca8199c39
Create Date: 2023-12-03 13:54:38.994188

"""

# revision identifiers, used by Alembic.
revision = 'b0c8f59c0344'
down_revision = '942ca8199c39'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
