"""init

Revision ID: b9418c818f6f
Revises: 160bf4d6dc8a
Create Date: 2023-12-01 16:14:48.016087

"""

# revision identifiers, used by Alembic.
revision = 'b9418c818f6f'
down_revision = '160bf4d6dc8a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
