"""init

Revision ID: bdecc0caad5d
Revises: cbb251365c6d
Create Date: 2023-12-03 17:45:14.560758

"""

# revision identifiers, used by Alembic.
revision = 'bdecc0caad5d'
down_revision = 'cbb251365c6d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
