"""init

Revision ID: cbb251365c6d
Revises: ef15647fb49a
Create Date: 2023-12-03 17:42:13.224942

"""

# revision identifiers, used by Alembic.
revision = 'cbb251365c6d'
down_revision = 'ef15647fb49a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
