"""init

Revision ID: cef50e81b78d
Revises: 78e74952014b
Create Date: 2023-12-03 15:13:02.813045

"""

# revision identifiers, used by Alembic.
revision = 'cef50e81b78d'
down_revision = '78e74952014b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
