"""init

Revision ID: d71b7d6174f0
Revises: 249376e26242
Create Date: 2023-12-03 01:29:12.398482

"""

# revision identifiers, used by Alembic.
revision = 'd71b7d6174f0'
down_revision = '249376e26242'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
