"""init

Revision ID: e1981361e1bf
Revises: bdecc0caad5d
Create Date: 2023-12-03 17:48:13.273742

"""

# revision identifiers, used by Alembic.
revision = 'e1981361e1bf'
down_revision = 'bdecc0caad5d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
