"""init

Revision ID: e2e46b3bcdaf
Revises: e4a4cec41273
Create Date: 2023-12-03 16:06:42.519019

"""

# revision identifiers, used by Alembic.
revision = 'e2e46b3bcdaf'
down_revision = 'e4a4cec41273'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
