"""init

Revision ID: e4a4cec41273
Revises: 509d768ab6f0
Create Date: 2023-12-03 15:39:34.214019

"""

# revision identifiers, used by Alembic.
revision = 'e4a4cec41273'
down_revision = '509d768ab6f0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
