"""init

Revision ID: e711c032d713
Revises: f822843c41bb
Create Date: 2023-12-03 01:53:24.215779

"""

# revision identifiers, used by Alembic.
revision = 'e711c032d713'
down_revision = 'f822843c41bb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
