"""init

Revision ID: ef15647fb49a
Revises: 2f3ff0cf1b1f
Create Date: 2023-12-03 17:36:17.945597

"""

# revision identifiers, used by Alembic.
revision = 'ef15647fb49a'
down_revision = '2f3ff0cf1b1f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
