"""init

Revision ID: f822843c41bb
Revises: 2aa630ca6c48
Create Date: 2023-12-03 01:51:22.643958

"""

# revision identifiers, used by Alembic.
revision = 'f822843c41bb'
down_revision = '2aa630ca6c48'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
